### ISSUE TITLE
Issue sending images

### ISSUE THREAD

**Issue by tbnritzdoge** [dirigeants/core#268]
So whenever I try to send an image URL or set an image in the embed constructor it removes `-photo-` from the URL string. 
This can be seen here https://ur-dad.is-inside.me/Z5osb9n7.png

**Comment by tbnritzdoge** [comment]
This behavior is also seen when sending `-photo-` as a string by itself. https://ur-dad.is-inside.me/GhhYSeS4.png

**Comment by bdistin** [comment]
-photo is being parsed as a flag. The eval command uses flags. If you need to turn off flagSupport for another given command you can use the https://klasa.js.org/#/docs/klasa/v0.5.0/class/Command?scrollTo=flagSupport option.
